name: Justin Scherer
favicon: null
layout_spectrum: 0.74864
typography_spectrum: 0.18593
title: Justin Scherer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e03940'
    - '#17315e'
    - '#ffffff'
    - '#517dac'
    - '#e4c6ca'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
