name: Justin Scherer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11601232411339879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e03940'
    - '#17315e'
    - '#ffffff'
    - '#517dac'
    - '#e4c6ca'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
