name: Justin Scherer
favicon: null
layout_spectrum: 0.50168
typography_spectrum: 0.17504
title: Justin Scherer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ada3a2'
    - '#f92b6c'
    - '#fb7381'
    - '#32a6a3'
    - '#844886'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
